### ISSUE TITLE
WebHook Start project does not run on directly from GitHub

### ISSUE THREAD

**Issue by sremiger1** [plaid/tutorial-resources#28] opened 2023-12-14 14:33 UTC
Could not get the webhook project to run from github
Created a fork and made the fixes

https://github.com/plaid/tutorial-resources/pull/27

1.  Missing package
2.  Incorrect require command
3.  I think this is for older node versions but the ? caused an error and had to change to a 2-step compare.

**Comment by phoenixy1** [comment] 2023-12-14 19:20
closing this out as per discussion on the linked PR the cause was incompatible version of Node (12) being used that has a different interface for the fs promises API:

https://github.com/nodejs/node/issues/35740

**Closed by phoenixy1** 2023-12-14 19:20 UTC
